### PR TITLE
test: add powershell version of RUNTESTS

### PR DESCRIPTION
**Pull request by peluse**
And some misc updates to unittests.ps1, also added 2 sub projects
to the .sln file.

---

This change is [Reviewable](https://reviewable.io/reviews/krzycz/nvml/8)

### CODE REVIEW

**Comment by krzycz** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[win/NVML.sln, line 226 [r1]](https://reviewable.io:443/reviews/krzycz/nvml/8#-KH0hvUoh-hIK6Oa1K6l:-KH0hvUpkD-g2IVcWTeY:221025515) ([raw file](https://github.com/krzycz/nvml/blob/fc4a37012680bd14696f569f590bb5e134fcdb42/win/NVML.sln#L226)):_
Same applies to blk_pool, I believe. Also, why not to enable Release config as well?

---

_[win/test/RUNTESTS.ps1, line 49 [r1]](https://reviewable.io:443/reviews/krzycz/nvml/8#-KH0p_TbsCC6y0KVsoJ5:-KH0p_TbsCC6y0KVsoJ6:-1638359296) ([raw file](https://github.com/krzycz/nvml/blob/fc4a37012680bd14696f569f590bb5e134fcdb42/win/test/RUNTESTS.ps1#L49)):_
These four options apply to tests under Valgrind.  Not sure if they are useful on Windows at all. 
Perhaps, we may need some other options that are aligned with AppVerifier features or something like that.

---

_[win/test/RUNTESTS.ps1, line 151 [r1]](https://reviewable.io:443/reviews/krzycz/nvml/8#-KH0s7PIvgXdtZZOoO42:-KH0s7PIvgXdtZZOoO43:160367930) ([raw file](https://github.com/krzycz/nvml/blob/fc4a37012680bd14696f569f590bb5e134fcdb42/win/test/RUNTESTS.ps1#L151)):_
???

---

_[win/test/RUNTESTS.ps1, line 265 [r1]](https://reviewable.io:443/reviews/krzycz/nvml/8#-KH0su0klwROShbHjf5H:-KH0su0klwROShbHjf5I:675980837) ([raw file](https://github.com/krzycz/nvml/blob/fc4a37012680bd14696f569f590bb5e134fcdb42/win/test/RUNTESTS.ps1#L265)):_
.ps1

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/krzycz/nvml/8)_

**Comment by peluse** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[win/test/RUNTESTS.ps1, line 49 [r1]](https://reviewable.io:443/reviews/krzycz/nvml/8#-KH0p_TbsCC6y0KVsoJ5:-KH5I9BaH33RcqAgK4RS:1649491558) ([raw file](https://github.com/krzycz/nvml/blob/fc4a37012680bd14696f569f590bb5e134fcdb42/win/test/RUNTESTS.ps1#L49)):_
yes, that's why I opened a new card about appveyor.  I'm not trying to solve everything with this pull request, just putting runtests.sh up there

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/krzycz/nvml/8)_

**Comment by peluse** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[win/test/RUNTESTS.ps1, line 49 [r1]](https://reviewable.io:443/reviews/krzycz/nvml/8#-KH0p_TbsCC6y0KVsoJ5:-KH5ILHVzYK2kqZPSgrS:-499146009) ([raw file](https://github.com/krzycz/nvml/blob/fc4a37012680bd14696f569f590bb5e134fcdb42/win/test/RUNTESTS.ps1#L49)):_
Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/krzycz/nvml/8)_

**Comment by peluse** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[win/NVML.sln, line 226 [r1]](https://reviewable.io:443/reviews/krzycz/nvml/8#-KH0hvUoh-hIK6Oa1K6l:-KH5IYgDacnsPRGp1TeK:-848647216) ([raw file](https://github.com/krzycz/nvml/blob/fc4a37012680bd14696f569f590bb5e134fcdb42/win/NVML.sln#L226)):_
I opened a new card to address all of the build flavors, there was some issue with blk_pool so I just added the ones now that are needed to run the current tests that are ported.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/krzycz/nvml/8)_

**Comment by peluse** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[win/NVML.sln, line 226 [r1]](https://reviewable.io:443/reviews/krzycz/nvml/8#-KH0hvUoh-hIK6Oa1K6l:-KH5IjJgGlFeFgOGzR-M:-499146009) ([raw file](https://github.com/krzycz/nvml/blob/fc4a37012680bd14696f569f590bb5e134fcdb42/win/NVML.sln#L226)):_
Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/krzycz/nvml/8)_

**Comment by peluse** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[win/test/RUNTESTS.ps1, line 151 [r1]](https://reviewable.io:443/reviews/krzycz/nvml/8#-KH0s7PIvgXdtZZOoO42:-KH5ImIvSO6zjDU2-54A:-1839016955) ([raw file](https://github.com/krzycz/nvml/blob/fc4a37012680bd14696f569f590bb5e134fcdb42/win/test/RUNTESTS.ps1#L151)):_
I have no idea what this comment "???" means or refers to

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/krzycz/nvml/8)_

**Comment by peluse** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[win/test/RUNTESTS.ps1, line 265 [r1]](https://reviewable.io:443/reviews/krzycz/nvml/8#-KH0su0klwROShbHjf5H:-KH5Iwiwl53CJ0h0HT99:-1415174301) ([raw file](https://github.com/krzycz/nvml/blob/fc4a37012680bd14696f569f590bb5e134fcdb42/win/test/RUNTESTS.ps1#L265)):_
what does this comment mean? Does reviewable just suck? There doesn't seem to be any context anywhere, the only thing I see is a comment that says "ps1"

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/krzycz/nvml/8)_

**Comment by krzycz** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[win/test/RUNTESTS.ps1, line 151 [r1]](https://reviewable.io:443/reviews/krzycz/nvml/8#-KH0s7PIvgXdtZZOoO42:-KH5Jh0yYNkTAAWkRCt1:1158127160) ([raw file](https://github.com/krzycz/nvml/blob/fc4a37012680bd14696f569f590bb5e134fcdb42/win/test/RUNTESTS.ps1#L151)):_
In Reviewable I can see some strange characters around "m".

---

_[win/test/RUNTESTS.ps1, line 265 [r1]](https://reviewable.io:443/reviews/krzycz/nvml/8#-KH0su0klwROShbHjf5H:-KH5KERwhknuoJ5G8Gqh:1406207329) ([raw file](https://github.com/krzycz/nvml/blob/fc4a37012680bd14696f569f590bb5e134fcdb42/win/test/RUNTESTS.ps1#L265)):_
"and edit testconfig.sh ..." => "and edit testconfig.ps1 ..."

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/krzycz/nvml/8)_

**Comment by peluse** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

_[win/test/RUNTESTS.ps1, line 151 [r1]](https://reviewable.io:443/reviews/krzycz/nvml/8#-KH0s7PIvgXdtZZOoO42:-KH5Ww6Q0qLfh8OEvzSI:-499146009) ([raw file](https://github.com/krzycz/nvml/blob/fc4a37012680bd14696f569f590bb5e134fcdb42/win/test/RUNTESTS.ps1#L151)):_
Done.

---

_[win/test/RUNTESTS.ps1, line 265 [r1]](https://reviewable.io:443/reviews/krzycz/nvml/8#-KH0su0klwROShbHjf5H:-KH5WygtoLnOlMzimVOD:-499146009) ([raw file](https://github.com/krzycz/nvml/blob/fc4a37012680bd14696f569f590bb5e134fcdb42/win/test/RUNTESTS.ps1#L265)):_
Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/krzycz/nvml/8)_

**Comment by krzycz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/krzycz/nvml/8#-:-KH5XUR0IttYKJ1EvYq5:1417088721)_

**Pull request merged**
