### PR TITLE
Address windows issue with UT and unique paths in log files

### PR DESCRIPTION
**Pull request by peluse**
On windows, ut_start() get args that include the full pathname
to the file even if a relative path is specified then the test
.exe is called.  Not sure this is the best way to address it,
but I simply truncate the path when logging filenames in Win
otherwise match files cannot be checked in and expect to work
from system to system.

Also added one more test.

---

This change is [Reviewable](https://reviewable.io/reviews/krzycz/nvml/7)

### CODE REVIEW

**Comment by krzycz** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

_[win/test/blk_nblock/out0.log.match, line 2 [r2]](https://reviewable.io:443/reviews/krzycz/nvml/7#-KFt0GjYzB2_doQnaNCV:-KFt0GjYzB2_doQnaNCW:-2067407816) ([raw file](https://github.com/krzycz/nvml/blob/c55f37ddffc952f1e79a2cccf09495f9a4545d5b/win/test/blk_nblock/out0.log.match#L2)):_
IMHO, this is not the right approach.  The _match_ script supports some tokens that can be embedded in a `*.match` file in case the output does not need to match exactly (see _match_ or _src/test/README_ for details).  So, instead of doing changes to `ut_start()`, I'd rather use `$(nW)` tokens here:

```
$(nW)\blk_nblock$(nW) $(nW)\testfile1 $(nW)\testfile2.512 ...
$(nW)\testfile1: pmemblk_create: Invalid argument
```

I believe that in most cases `*.match` files could be exactly the same for Linux and Windows. Perhaps the only problem is with '/' and '\' used in file paths.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/krzycz/nvml/7)_

**Comment by peluse** [comment]
BTW, yeah they will be the same as far as I can tell except for \ vs / which we could address if we wanted to and just use the match files in the linux portion of the dir tree but I don't think its a huge problem to have unique ones for windows as we may have places where the match files are different.  Actually, we already do where we test for super huge files on linux but not on windows :)

Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

_[win/test/blk_nblock/out0.log.match, line 2 [r2]](https://reviewable.io:443/reviews/krzycz/nvml/7#-KFt0GjYzB2_doQnaNCV:-KFtE0qciUkC4hPuQCLT:71561736) ([raw file](https://github.com/krzycz/nvml/blob/c55f37ddffc952f1e79a2cccf09495f9a4545d5b/win/test/blk_nblock/out0.log.match#L2)):_
OK, cool.  I was wondering what those were :)  I'll take a look later this afternoon and let you know if I have questions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/krzycz/nvml/7)_

**Comment by krzycz** [comment]
And one more style nit - please follow the git commit message convention:
http://pmem.io/2014/09/09/git-workflow.html

---

Reviewed 1 of 9 files at r1, 1 of 2 files at r2, 29 of 35 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[win/test/blk_non_zero/TEST2.ps1, line 37 [r3]](https://reviewable.io:443/reviews/krzycz/nvml/7#-KGXbTW7Z4RgvYROQLeq:-KGXbTW8tFZkMSQaLlBv:-1757620407) ([raw file](https://github.com/krzycz/nvml/blob/1f444bbb7405599c31110df670d6b7320c54de64/win/test/blk_non_zero/TEST2.ps1#L37)):_
By convention, we use "XXX" tag instead of "TBD"/"TODO"/...

---

_[win/test/blk_non_zero/TEST2.ps1, line 56 [r3]](https://reviewable.io:443/reviews/krzycz/nvml/7#-KGX_Af-fU2PraQra_2I:-KGX_Af0hvIu7MXs7-gl:2112231300) ([raw file](https://github.com/krzycz/nvml/blob/1f444bbb7405599c31110df670d6b7320c54de64/win/test/blk_non_zero/TEST2.ps1#L56)):_
Would be nice to get rid of this: "....\x64\debug".
Also, on Linux the tests are automatically executed for debug and nondebug builds. With hardcoded path to debug build, it can;t be done on Windows.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/krzycz/nvml/7#-:-KGXc7pIl_Xo40svTaca:-315042910)_

**Comment by peluse** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[win/test/blk_non_zero/TEST2.ps1, line 56 [r3]](https://reviewable.io:443/reviews/krzycz/nvml/7#-KGX_Af-fU2PraQra_2I:-KGXkPDMNmPZIW4n9Ybi:-84435484) ([raw file](https://github.com/krzycz/nvml/blob/1f444bbb7405599c31110df670d6b7320c54de64/win/test/blk_non_zero/TEST2.ps1#L56)):_
this points to the test executable only and as discussed in the meetings, there's no real value in building the different flavors of it.  The different flavors of the library are what's important

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/krzycz/nvml/7)_

**Comment by krzycz** [comment]
Reviewed 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/krzycz/nvml/7)_

**Comment by peluse** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[win/test/blk_non_zero/TEST2.ps1, line 37 [r3]](https://reviewable.io:443/reviews/krzycz/nvml/7#-KGXbTW7Z4RgvYROQLeq:-KGXofQ4i9eS0rdcPEFo:-499146009) ([raw file](https://github.com/krzycz/nvml/blob/1f444bbb7405599c31110df670d6b7320c54de64/win/test/blk_non_zero/TEST2.ps1#L37)):_
Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/krzycz/nvml/7)_

**Comment by peluse** [comment]
done

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/krzycz/nvml/7#-:-KGXoq39b14RKv3OwGQa:677588487)_

**Pull request merged**
